# Generated by Django 5.1 on 2024-08-21 11:34

import django.core.validators
import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('dpt_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=255)),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.faculty')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.level')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_num', models.CharField(editable=False, max_length=8, unique=True)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('specialization', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('HoD', 'Head of Department'), ('Lecturer', 'Lecturer')], max_length=20)),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.department')),
            ],
        ),
    ]
