# Generated by Django 5.1 on 2024-09-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
