# Generated by Django 5.1 on 2024-09-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
