# Generated by Django 5.1 on 2024-09-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('case_study', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('check_status', models.BooleanField(default=False)),
                ('approval_status', models.BooleanField(default=False)),
                ('completion_status', models.BooleanField(default=False)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_projects', to='projects.student')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.department')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.supervisor')),
            ],
        ),
    ]
