# Generated by Django 5.1 on 2024-09-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_user_student_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('STUDENT', 'Student'), ('REGISTER', 'Register'), ('ADMIN', 'Admin')], default='STUDENT', max_length=25),
        ),
    ]
