# Generated by Django 5.1 on 2024-09-26 05:21

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
