# Generated by Django 5.1 on 2024-09-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_student_account_alter_supervisor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('STUDENT', 'Student'), ('REGISTER', 'Register'), ('ADMIN', 'Admin'), ('HOD', 'Hod')], default='STUDENT', max_length=25),
        ),
    ]
