# Generated by Django 5.1 on 2024-09-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_accademic_year_alter_project_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accademic_year',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
