# Generated by Django 5.1 on 2024-10-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_supervisor_profile_pic'),
        ('projects', '0010_alter_project_accademic_year'),
    ]

    operations = [
    ]
