# Generated by Django 5.1 on 2024-10-09 13:40

import django.core.validators
import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_accademic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.student')),
            ],
        ),
    ]
