# Generated by Django 5.1 on 2024-10-03 10:43

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_merge_20241003_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='accademic_year',
            new_name='academic_year',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(default=-1, upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
