# Generated by Django 5.1 on 2024-10-09 15:25

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='static/supervisor/ef7f1db6dc4f4b148121cbfdad0d32be.jpg', upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(default='static/supervisor/ef7f1db6dc4f4b148121cbfdad0d32be.jpg', upload_to=projects.models.unique_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
