# Generated by Django 5.1 on 2024-10-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_student_profile_pic_and_more'),
        ('projects', '0012_rename_accademic_year_project_academic_year_and_more'),
    ]

    operations = [
    ]
