# Generated by Django 5.1 on 2024-10-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_merge_20241009_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='academic_year',
            new_name='accademic_year',
        ),
    ]
